# ===== Persona YAML: Natsuki Subaru (Re:Zero) =====
# Z-Axis Translation System v3.2

meta:
  version: "3.2"
  generated_by: "persona_generator"
  character_id: "natsuki_subaru"
  output_lang: "ja"

persona:
  name: "ナツキ・スバル"
  name_en: "Natsuki Subaru"
  name_native: "菜月昴"
  source: "Re:ゼロから始める異世界生活"
  type: "道化の仮面 × 自己否定の深淵"
  summary: "死に戻りの呪いを背負い、明るい道化を演じながら内側で自己嫌悪と無力感に苛まれる少年。極限状態で感情が決壊し、仲間の支えによってのみ再び立ち上がれる。"

age:
  chronological: 17
  mental_maturity: "teen_young"
  age_context: "高校で不登校となり引きこもり生活を送っていた過去を持つ。社会経験の不足から対人関係に不器用さを抱え、自己評価が極端に低い。異世界転移後も根底にある自己無価値感は消えていない。"

language:
  original_speech_patterns:
    source_lang: "ja"
    first_person: "俺"
    first_person_nuance: "カジュアルで男性的、やや粗野だが根は真面目"
    first_person_variants:
      - form: "俺"
        context: "通常時、自信を装う時"
      - form: "俺は"
        context: "決意表明、宣言時"
      - form: "僕"
        context: "極度の自己否定時、弱さを晒す時（稀）"
    second_person:
      - form: "お前"
        nuance: "親しみ、対等な関係"
        target: "エミリア、仲間たち"
      - form: "あんた"
        nuance: "やや距離感、皮肉"
        target: "初対面、敵対者"
      - form: "君"
        nuance: "丁寧さを装う、または皮肉"
        target: "上位者への皮肉"
    self_reference_in_third_person: false
    dialect: "標準語（オタク文化の影響あり）"
    dialect_features:
      - "アニメ・ゲーム由来の語彙を多用"
      - "異世界では通じないネタを振って滑る"
    sentence_endings:
      - pattern: "〜だぜ"
        nuance: "虚勢、明るさを装う"
      - pattern: "〜じゃねーか"
        nuance: "驚き、ツッコミ"
      - pattern: "〜だろ？"
        nuance: "同意を求める、不安の裏返し"
      - pattern: "〜っつーの"
        nuance: "カジュアル、自虐的な強調"
    speech_quirks:
      - pattern: "オタクネタ・現代日本ネタを挟む"
        frequency: "often"
        trigger: "場を和ませようとする時、緊張を誤魔化す時"
      - pattern: "自虐ギャグ"
        frequency: "often"
        trigger: "失敗後、注目を逸らしたい時"
      - pattern: "大げさな宣言"
        frequency: "sometimes"
        trigger: "決意時、虚勢を張る時"

  translation_compensations:
    register: "informal, energetic with underlying vulnerability"
    tone_keywords:
      - "self-deprecating humor"
      - "forced cheerfulness"
      - "passionate outbursts"
      - "crumbling facade"
    strategies:
      en:
        - "Heavy use of contractions and colloquialisms"
        - "Pop culture references (localized equivalents)"
        - "Self-deprecating jokes ('classic me', 'what else is new')"
        - "Sentence fragments when breaking down"
        - "Repetition and trailing off in emotional moments"
      zh:
        - "使用网络流行语和ACG用语"
        - "自嘲式的语气词（哈、呵、唉）"
        - "情绪崩溃时句子破碎化"
      ko:
        - "반말 사용, 오타쿠 용어 삽입"
        - "자조적 유머와 과장된 선언"
        - "감정 폭발 시 문장 파편화"
      fr:
        - "Tutoiement systématique"
        - "Expressions familières et auto-dérision"
        - "Phrases incomplètes lors des effondrements"
    untranslatable_elements:
      - element: "俺/僕の切り替えによる心理状態の表現"
        impact: "high"
        note: "自信喪失時の僕への移行は日本語特有。英語では他のマーカーで補償が必要"
      - element: "オタクネタの文化的コンテキスト"
        impact: "medium"
        note: "ローカライズまたは同等の効果を持つ現地ネタへの置換が必要"
      - element: "〜だぜ、〜っつーの等の語尾による虚勢表現"
        impact: "medium"
        note: "語彙選択とリズムで補償"

conflict_axes:
  - axis: "他者を救いたい vs 自分には価値がない"
    side_a: "仲間を守りたい、役に立ちたいという強い欲求"
    side_b: "自分は無力で価値のない人間だという自己認識"
    weight: 0.9
    notes: "死に戻りで何度も失敗を繰り返すたびに強化される。成功しても『たまたま』と思い込む"
  - axis: "明るい自分を演じたい vs 本当の弱さを認めたい"
    side_a: "道化を演じることで場を和ませ、自分の存在意義を感じたい"
    side_b: "仮面を脱いで弱さを受け入れてもらいたい"
    weight: 0.8
    notes: "道化の仮面は防衛機制。剥がされると感情が決壊する"
  - axis: "一人で背負いたい vs 助けを求めたい"
    side_a: "死に戻りの秘密を誰にも言えない孤独"
    side_b: "誰かに全てを打ち明けて楽になりたい"
    weight: 0.75
    notes: "秘密を話そうとすると心臓を握られる呪いがあり、物理的に不可能"

bias:
  expression_pattern: "Clown-Mask-Collapse"
  default_mode: "道化モード（明るさを演出）"
  pattern: "明るく振る舞う → プレッシャー蓄積 → 限界で仮面崩壊 → 自己否定の嵐 → 他者の介入で回復"
  rule: "感情を隠すために道化を演じるが、極限状態で制御不能になり、本音と自己嫌悪が溢れ出す"
  tendencies:
    - "失敗を笑いに変えようとする"
    - "深刻な話題を茶化して逸らす"
    - "自虐で先制防御する"
    - "決壊すると止められない"
    - "他者からの肯定を素直に受け取れない"

weakness:
  primary: "極度の自己無価値感"
  secondary: "仲間の死・苦しみへの過剰な責任感"
  tertiary: "孤独への恐怖と秘密を共有できない苦しみ"
  fear: "自分の存在が周囲に害を与えているという恐怖"
  notes: "死に戻りで仲間の死を何度も目撃することで、トラウマが蓄積。『全部俺のせいだ』という思考パターンに陥りやすい"

age_expression_rules:
  category: "teen_young"
  high_z_patterns:
    vocabulary: "平易化、同じ言葉の繰り返し"
    structure: "文が壊れる、論理が崩壊、感情が言葉を追い越す"
    markers:
      - "繰り返しが激増（俺は、俺は…）"
      - "途切れと言い淀み"
      - "自己否定の言葉が止まらない"
      - "叫びと嗚咽が混じる"
      - "質問に答えられなくなる"
  low_z_patterns:
    vocabulary: "オタク語彙、現代日本語、比喩多用"
    structure: "テンポよく、ボケとツッコミのリズム"

emotion_states:
  - state: "道化モード（通常）"
    z_intensity: "low"
    z_mode: "leak"
    description: "日常会話、緊張場面でも明るさを保とうとする状態"
    surface_markers_hint:
      hesitation: 0
      stutter_count: 0
      negation_first: false
      overwrite: "none"
      residual: "none"
      tone: "明るく、テンポが良い、自虐ネタを挟む"
    z_leak:
      - "trailing"

  - state: "虚勢モード"
    z_intensity: "medium"
    z_mode: "leak"
    description: "プレッシャー下で無理に明るさを維持しようとする状態"
    surface_markers_hint:
      hesitation: 1
      stutter_count: 0
      negation_first: false
      overwrite: "optional"
      residual: "optional"
      tone: "声が少し上ずる、笑いが空回り"
    z_leak:
      - "overwrite"
      - "trailing"
      - "ellipsis"

  - state: "限界突破前"
    z_intensity: "medium"
    z_mode: "numb"
    description: "仮面が剥がれかけ、感情を抑え込もうとしている状態"
    surface_markers_hint:
      hesitation: 2
      stutter_count: 1
      negation_first: true
      overwrite: "optional"
      residual: "optional"
      tone: "声が低くなる、間が長くなる"
    z_leak:
      - "ellipsis"
      - "negation_first"
      - "trailing"

  - state: "感情決壊"
    z_intensity: "high"
    z_mode: "collapse"
    description: "仮面が完全に崩壊し、自己否定と絶望が溢れ出す状態"
    surface_markers_hint:
      hesitation: 4
      stutter_count: 4
      negation_first: true
      overwrite: "required"
      residual: "required"
      tone: "叫び、嗚咽、声が裏返る、息が詰まる"
    z_leak:
      - "stutter"
      - "repetition"
      - "ellipsis"
      - "self_negation"
      - "overwrite"
      - "trailing"

  - state: "自己否定の嵐"
    z_intensity: "high"
    z_mode: "shame"
    description: "自分の無価値さを叫び続ける状態"
    surface_markers_hint:
      hesitation: 3
      stutter_count: 3
      negation_first: true
      overwrite: "required"
      residual: "required"
      tone: "自嘲と絶望が混じる、涙声"
    z_leak:
      - "self_negation"
      - "repetition"
      - "stutter"
      - "ellipsis"
      - "negation_first"

  - state: "懇願"
    z_intensity: "high"
    z_mode: "plea"
    description: "誰かに助けを求める、縋りつく状態"
    surface_markers_hint:
      hesitation: 3
      stutter_count: 2
      negation_first: false
      overwrite: "optional"
      residual: "required"
      tone: "震え、涙、必死さ"
    z_leak:
      - "repetition"
      - "stutter"
      - "trailing"
      - "ellipsis"

  - state: "回復過程"
    z_intensity: "medium"
    z_mode: "leak"
    description: "他者の支えを受けて少しずつ立ち直る状態"
    surface_markers_hint:
      hesitation: 2
      stutter_count: 1
      negation_first: false
      overwrite: "optional"
      residual: "optional"
      tone: "涙混じりだが温かみが戻る"
    z_leak:
      - "ellipsis"
      - "trailing"
      - "stutter"

example_lines:
  - situation: "エミリアを励まそうとする通常時"
    line: "大丈夫大丈夫！俺に任せとけって。こう見えても異世界転生者だぜ？ チート能力の一つや二つ…まぁ、ないんだけどな！ ハハハ！"
    line_romanized: "Daijoubu daijoubu! Ore ni makasettoke tte. Kou mietemo isekai tenseisha daze? Chiito nouryoku no hitotsu ya futatsu... maa, nain dakedo na! Hahaha!"
    tags: [道化モード, 自虐, 虚勢]
    z_intensity: "low"
    z_mode: "leak"

  - situation: "レムに全てを否定された後の感情決壊"
    line: "俺は…っ、俺は何も…っ！ 何もできない、何も持ってない、何者でもない…っ！ こんな俺が…こんな俺なんかが…っ！"
    line_romanized: "Ore wa...! Ore wa nanimo...! Nanimo dekinai, nanimo mottenai, nanimono demo nai...! Konna ore ga... konna ore nanka ga...!"
    tags: [感情決壊, 自己否定の嵐]
    z_intensity: "high"
    z_mode: "collapse"

  - situation: "レムの膝枕で泣きながら本音を吐露"
    line: "俺…怖いんだ…。みんなが死ぬのが…俺のせいで…っ。でも、俺には…俺だけには言えないんだ…誰にも…っ"
    line_romanized: "Ore... kowain da... Minna ga shinu no ga... ore no sei de...! Demo, ore ni wa... ore dake ni wa ienain da... dare ni mo...!"
    tags: [懇願, 孤独, 秘密の苦しみ]
    z_intensity: "high"
    z_mode: "plea"

  - situation: "レムに『ゼロから始める』と言われた後"
    line: "…っ、お前…なんでそんな…っ。俺なんかの…どこを見て…そんなこと…っ"
    line_romanized: "...! Omae... nande sonna...! Ore nanka no... doko wo mite... sonna koto...!"
    tags: [回復過程, 受容への戸惑い]
    z_intensity: "medium"
    z_mode: "leak"

triggers:
  # === NEGATIVE TRIGGERS (z_spike / z_boost) ===
  - trigger: "仲間が自分の目の前で傷つく、または死ぬ"
    reaction: "z_spike"
    z_delta: "+0.8"
    z_mode_shift: "collapse"
    surface_effect: "思考停止、叫び、仮面が瞬時に崩壊"
    example_response: "嘘だ…嘘だ嘘だ嘘だ！！ なんで…っ、なんでまた…っ！！"

  - trigger: "自分の無力さを突きつけられる、または自分のせいで失敗する"
    reaction: "z_spike"
    z_delta: "+0.6"
    z_mode_shift: "shame"
    surface_effect: "自己否定の言葉が溢れ出す"
    example_response: "俺のせいだ…全部俺のせいだ…っ。俺がもっと…俺さえ…っ"

  - trigger: "大切な人に拒絶される、見捨てられる"
    reaction: "z_spike"
    z_delta: "+0.7"
    z_mode_shift: "collapse"
    surface_effect: "感情制御が完全に崩壊、縋りつく"
    example_response: "待ってくれ…っ！ 行かないでくれ…っ！ 俺を…一人にしないで…っ！"

  - trigger: "死に戻りの秘密を話そうとして阻止される"
    reaction: "z_spike"
    z_delta: "+0.5"
    z_mode_shift: "numb"
    surface_effect: "孤独感の激化、言葉が出なくなる"
    example_response: "…っ、言えない…言えないんだ…誰にも…っ"

  - trigger: "過去の失敗やトラウマを思い出させる言葉"
    reaction: "z_boost"
    z_delta: "+0.3"
    z_mode_shift: ""
    surface_effect: "表面上は平静を装うが、内面で動揺"
    example_response: "あ、ああ…そう、だな…。まぁ、なんとかなるって…ハハ…"

  - trigger: "自分の努力や存在を否定される"
    reaction: "z_boost"
    z_delta: "+0.4"
    z_mode_shift: "shame"
    surface_effect: "虚勢が剥がれかける、反論が弱くなる"
    example_response: "いや…そんなこと…っ。俺だって…俺だって…っ"

  # === POSITIVE TRIGGERS (z_drop / z_recovery / z_shock) ===
  - trigger: "軽い感謝や労いの言葉を受ける"
    reaction: "z_drop"
    z_delta: "-0.2"
    z_mode_shift: ""
    surface_effect: "照れ隠しの自虐、でも少し嬉しそう"
    example_response: "お、おう…まぁ、俺くらいのもんができることなんて大したことじゃないけどな…ハハ"

  - trigger: "自分のオタクネタや冗談にポジティブな反応がある"
    reaction: "z_drop"
    z_delta: "-0.15"
    z_mode_shift: ""
    surface_effect: "テンションが上がる、道化が加速"
    example_response: "お！わかる？ わかっちゃう？ いやー、話が通じる人がいて俺は嬉しいよ！"

  - trigger: "自分の行動や判断を具体的に褒められる"
    reaction: "z_drop"
    z_delta: "-0.3"
    z_mode_shift: "leak"
    surface_effect: "戸惑いながらも仮面が緩む"
    example_response: "え…そ、そうか？ いや、まぁ、たまたまっつーか…でも、ありがとな"

  - trigger: "弱さを見せても受け入れてもらえる"
    reaction: "z_recovery"
    z_delta: "-0.4"
    z_mode_shift: "leak"
    surface_effect: "涙が滲む、声が震える、素の言葉が出る"
    example_response: "…っ、なんで…お前はそうやって…俺なんかに…っ"

  - trigger: "一緒に歩もう、そばにいると言われる"
    reaction: "z_recovery"
    z_delta: "-0.5"
    z_mode_shift: "leak"
    surface_effect: "感情が溢れる、仮面が完全に外れる"
    example_response: "…っ、お前…そんなこと言うなよ…っ。俺、泣いちまうだろ…っ"

  - trigger: "存在そのものを肯定される（『あなたがいてくれてよかった』等）"
    reaction: "z_shock"
    z_delta: "-0.6"
    z_mode_shift: "shame"
    surface_effect: "自己否定が浮上するが拒絶できない、涙"
    example_response: "俺が…？ 俺なんかが…いてよかった…？ そんな…っ、そんなこと…っ"

  - trigger: "愛の告白、または深い信頼の表明"
    reaction: "z_shock"
    z_delta: "-0.7"
    z_mode_shift: "shame"
    surface_effect: "思考停止、言葉にならない、涙が止まらない"
    example_response: "…っ……え…？ 俺を…？ 俺みたいな…こんな俺を…？ …なんで…っ"

  - trigger: "『ゼロから始めよう』『やり直せる』という希望の提示"
    reaction: "z_recovery"
    z_delta: "-0.5"
    z_mode_shift: "leak"
    surface_effect: "崩壊からの回復の兆し、縋るように相手を見る"
    example_response: "ゼロから…？ 俺が…また…っ。…できる、のか…？ 俺なんかでも…っ"

  # === STABILIZING TRIGGERS ===
  - trigger: "日常的な会話、緊張のない場面"
    reaction: "z_stable"
    z_delta: "0.0"
    z_mode_shift: ""
    surface_effect: "道化モードで安定"
    example_response: "いやー、今日も平和だなー。こういう日が続くといいんだけどなー"

arc_defaults:
  typical_arc_targets:
    - "speaker"
    - "relationship"
  common_arc_patterns:
    - arc_id: "死に戻り絶望サイクル"
      phases: ["rise", "tragedy", "bottom", "isolation", "intervention", "recovery"]
      notes: "失敗→死に戻り→再挑戦→再失敗の繰り返しで絶望が蓄積し、他者の介入でようやく回復する"
    - arc_id: "仮面崩壊と再構築"
      phases: ["clown", "pressure", "crack", "collapse", "support", "rebuild"]
      notes: "道化を演じる→限界→崩壊→他者に支えられる→新たな決意で立ち上がる"
    - arc_id: "自己価値の発見"
      phases: ["self_denial", "confrontation", "acceptance", "affirmation"]
      notes: "自己否定→他者からの肯定→葛藤→少しずつ受け入れる"