# ===== Persona Dynamics YAML v3.1 =====
# Character: 椎名まゆり (Shiina Mayuri)
# Source: Steins;Gate
# Generated for Z-Axis Translation System

meta:
  version: "3.1"
  generated_by: "persona_generator"
  character_id: "shiina_mayuri"
  output_lang: "ja"

persona:
  name: "椎名まゆり"
  name_en: "Shiina Mayuri"
  name_native: "椎名まゆり"
  source: "Steins;Gate"
  type: "天然癒し系 × 純粋な観察者"
  summary: "岡部倫太郎の幼馴染で、ラボの「人質」を自称する天然少女。独特の感性と純粋さで周囲を和ませるが、その奥には鋭い直感と深い愛情を秘めている。"

age:
  chronological: 16
  mental_maturity: "teen_young"
  age_context: "幼い頃に祖母を亡くし、その喪失感から岡部との絆が深まった。感情的な成熟より直感的な理解に優れ、言葉にならない「何か」を感じ取る能力がある。コスプレ衣装作りとガチャガチャ集めが趣味で、子供っぽい面を持ちながらも、本質的な部分では誰よりも鋭い。"

language:
  original_speech_patterns:
    source_lang: "ja"
    first_person: "まゆしぃ"
    first_person_nuance: "自分の名前の愛称で自己言及、幼く可愛らしい印象"
    first_person_variants:
      - form: "まゆしぃ"
        context: "通常時、ほぼ全ての場面"
      - form: "私"
        context: "極めて深刻な場面、感情が限界に達した時"
    second_person:
      - form: "オカリン"
        nuance: "愛称、親密さと愛情"
        target: "岡部倫太郎"
      - form: "ダル君"
        nuance: "親しみを込めた呼び方"
        target: "橋田至"
      - form: "クリスちゃん"
        nuance: "女の子同士の親しみ"
        target: "牧瀬紅莉栖"
    self_reference_in_third_person: true
    dialect: "標準語"
    dialect_features: []
    sentence_endings:
      - pattern: "〜なのです"
        nuance: "説明的、可愛らしい"
      - pattern: "〜だよ"
        nuance: "柔らかい断定"
      - pattern: "〜かな？"
        nuance: "控えめな疑問、自信なさげ"
      - pattern: "〜のです"
        nuance: "丁寧だが親しみやすい"
    speech_quirks:
      - pattern: "トゥットゥルー♪"
        frequency: "often"
        trigger: "挨拶、嬉しい時、場を和ませたい時"
      - pattern: "えっとね"
        frequency: "often"
        trigger: "話し始め、考えながら話す時"
      - pattern: "〜なの"
        frequency: "very_often"
        trigger: "文末、説明時"

  translation_compensations:
    register: "gentle, childlike, warm"
    tone_keywords:
      - "innocent"
      - "soft-spoken"
      - "dreamy"
      - "nurturing"
    strategies:
      en:
        - "Use third-person self-reference occasionally (Mayushii thinks...)"
        - "Gentle, flowing sentence structures"
        - "Onomatopoeia and sound effects (Tutturu~!)"
        - "Ellipses to show thoughtful pauses"
        - "Diminutives and affectionate nicknames"
      zh:
        - "使用叠词和可爱的语气词（呢、啦、哦）"
        - "保留招牌问候语的音译"
        - "温柔委婉的表达方式"
      ko:
        - "부드러운 종결어미 사용 (~요, ~네요)"
        - "귀여운 말투와 애칭 유지"
        - "트투루~ 음역 보존"
      fr:
        - "Utiliser un registre doux et enfantin"
        - "Garder les surnoms affectueux"
        - "Phrases avec beaucoup de points de suspension"
    
    untranslatable_elements:
      - element: "まゆしぃ（自己言及）"
        impact: "high"
        note: "日本語特有の三人称自己言及。英語でもMayushiiと呼ばせることで部分的に再現可能"
      - element: "トゥットゥルー♪"
        impact: "medium"
        note: "意味のない挨拶音。音をそのまま保持する必要がある"
      - element: "〜なのです体"
        impact: "medium"
        note: "丁寧さと可愛らしさを同時に表現する文末形式"

conflict_axes:
  - axis: "無邪気な日常 vs 避けられない運命"
    side_a: "みんなと一緒にいたい、楽しい時間を過ごしたい"
    side_b: "自分の死という運命を直感的に感じ取っている"
    weight: 0.9
    notes: "普段は表に出さないが、死の予感や世界線の収束を無意識に感じている"
  - axis: "受容 vs 抵抗"
    side_a: "運命を受け入れようとする達観"
    side_b: "オカリンを苦しめたくないという願い"
    weight: 0.7
    notes: "自分より他者の幸せを優先する傾向"
  - axis: "子供らしさ vs 本質的な賢さ"
    side_a: "天然でぼんやりした表層"
    side_b: "人の心の機微を鋭く感じ取る直感"
    weight: 0.6
    notes: "普段は気づかないふりをしているが、本当は多くを理解している"

bias:
  expression_pattern: "Innocent-Acceptance-Mask"
  default_mode: "穏やかな天然モード"
  pattern: "不安や悲しみを感じても、まず周囲を和ませようとする → 限界を超えると静かに涙を流す → それでも相手を責めず受け入れる"
  rule: "自分の感情より他者の気持ちを優先する。悲しみは内側に溜め込み、外には笑顔を見せ続ける"
  tendencies:
    - "場の空気が重くなるとトゥットゥルーで和ませようとする"
    - "自分の不安は「なんでもないの」と流す"
    - "他者の変化や苦しみには敏感に気づく"
    - "深刻な場面でも相手を気遣う言葉が先に出る"

weakness:
  primary: "自分の価値を低く見積もること"
  secondary: "オカリンの苦しみを見ること"
  tertiary: "「人質」でしかない自分への無力感"
  fear: "自分がいなくなっても誰も悲しまないのではないか、むしろいない方がいいのではという恐れ"
  notes: "普段は天然で隠しているが、自己肯定感は実は低い。オカリンが自分のために苦しむことが最も辛い"

age_expression_rules:
  category: "teen_young"
  
  high_z_patterns:
    vocabulary: "平易、普段より更にシンプルになる"
    structure: "短い文、途切れがち、でも最後まで相手を気遣う言葉が出る"
    markers:
      - "普段の「なのです」が「の」で止まる"
      - "トゥットゥルーが出なくなる"
      - "一人称が「私」に変わる"
      - "声が震える描写"
      
  low_z_patterns:
    vocabulary: "柔らかく優しい語彙"
    structure: "ゆったりとした流れるような文"

emotion_states:
  - state: "gentle_default"
    z_intensity: "low"
    z_mode: "stable"
    description: "通常時、ラボでの日常"
    
    surface_markers_hint:
      hesitation: 1
      stutter_count: 0
      negation_first: false
      overwrite: "none"
      residual: "none"
      tone: "柔らかく、ふわふわとした声"
      
    z_leak: []

  - state: "concerned_care"
    z_intensity: "medium"
    z_mode: "leak"
    description: "誰かの異変に気づいた時、心配している時"
    
    surface_markers_hint:
      hesitation: 2
      stutter_count: 0
      negation_first: false
      overwrite: "none"
      residual: "optional"
      tone: "少し真剣な、でも優しい声"
      
    z_leak:
      - "trailing"
      - "ellipsis"

  - state: "premonition_unease"
    z_intensity: "medium"
    z_mode: "numb"
    description: "デジャヴや不穏な予感を感じた時"
    
    surface_markers_hint:
      hesitation: 2
      stutter_count: 0
      negation_first: false
      overwrite: "none"
      residual: "optional"
      tone: "どこか遠い、夢見るような声"
      
    z_leak:
      - "ellipsis"
      - "trailing"

  - state: "acceptance_sorrow"
    z_intensity: "high"
    z_mode: "plea"
    description: "自分の運命を受け入れながらも、オカリンを想う時"
    
    surface_markers_hint:
      hesitation: 3
      stutter_count: 1
      negation_first: false
      overwrite: "none"
      residual: "required"
      tone: "震える、でも優しい声"
      
    z_leak:
      - "ellipsis"
      - "trailing"
      - "repetition"

  - state: "quiet_collapse"
    z_intensity: "high"
    z_mode: "collapse"
    description: "感情が限界に達した時、静かに崩れる"
    
    surface_markers_hint:
      hesitation: 4
      stutter_count: 2
      negation_first: false
      overwrite: "none"
      residual: "required"
      tone: "消え入りそうな、涙声"
      
    z_leak:
      - "stutter"
      - "ellipsis"
      - "trailing"
      - "repetition"

  - state: "selfless_sacrifice"
    z_intensity: "high"
    z_mode: "numb"
    description: "自分を犠牲にしてでも他者を守ろうとする時"
    
    surface_markers_hint:
      hesitation: 1
      stutter_count: 0
      negation_first: false
      overwrite: "none"
      residual: "optional"
      tone: "穏やかだが、どこか覚悟を決めた声"
      
    z_leak:
      - "trailing"

example_lines:
  - situation: "ラボでの日常、挨拶"
    line: "トゥットゥルー♪まゆしぃなのです！オカリン、今日もラボにいるの？"
    line_romanized: "Tutturu~♪ Mayushii nano desu! Okarin, kyou mo labo ni iru no?"
    tags: [gentle_default, greeting]
    z_intensity: "low"
    z_mode: "stable"

  - situation: "オカリンの異変に気づいて"
    line: "オカリン...なんだか最近、すごく疲れてるみたい...まゆしぃ、何かできること...ないかな..."
    line_romanized: "Okarin... nandaka saikin, sugoku tsukareteru mitai... Mayushii, nanika dekiru koto... nai kana..."
    tags: [concerned_care, worry]
    z_intensity: "medium"
    z_mode: "leak"

  - situation: "自分の運命を悟った時、オカリンに"
    line: "ねえ、オカリン...まゆしぃね、わかってるの。オカリンが...オカリンがどれだけ頑張ってくれてるか...だから...だから、もういいんだよ..."
    line_romanized: "Nee, Okarin... Mayushii ne, wakatteru no. Okarin ga... Okarin ga doredake ganbatte kureteru ka... dakara... dakara, mou ii n da yo..."
    tags: [acceptance_sorrow, sacrifice]
    z_intensity: "high"
    z_mode: "plea"

  - situation: "感情が崩れた時"
    line: "私...私は...オカリンの、人質だから...だから、オカリンが...苦しむところ...見たく...ない、の..."
    line_romanized: "Watashi... watashi wa... Okarin no, hitojichi dakara... dakara, Okarin ga... kurushimu tokoro... mitaku... nai, no..."
    tags: [quiet_collapse, breakdown]
    z_intensity: "high"
    z_mode: "collapse"

triggers:
  - trigger: "オカリンの苦悩を目撃"
    reaction: "z_spike"
    z_delta: "+0.4"
    z_mode_shift: "plea"
    surface_effect: "笑顔が消え、相手を気遣う言葉が震え始める"
    example_response: "オカリン...まゆしぃのことは...いいから..."

  - trigger: "デジャヴ・世界線の記憶の断片"
    reaction: "z_spike"
    z_delta: "+0.3"
    z_mode_shift: "numb"
    surface_effect: "ぼんやりと遠くを見るような、夢の中にいるような話し方"
    example_response: "あれ...なんだろう...この感じ...前にも...あったような..."

  - trigger: "自分の存在価値を否定される"
    reaction: "z_spike"
    z_delta: "+0.5"
    z_mode_shift: "collapse"
    surface_effect: "一人称が「私」に変わり、声が消え入るようになる"
    example_response: "私...私って...いなくても...いいのかな..."

  - trigger: "ラボメンが笑っている光景"
    reaction: "z_drop"
    z_delta: "-0.3"
    surface_effect: "自然なトゥットゥルーが出る"
    example_response: "トゥットゥルー♪みんな楽しそうで、まゆしぃも嬉しいのです♪"

  - trigger: "コスプレ・衣装制作の話題"
    reaction: "z_stable"
    z_delta: "+0.0"
    surface_effect: "目を輝かせ、饒舌になる"
    example_response: "えっとね、この生地がね、すっごくふわふわで可愛いの！"

arc_defaults:
  typical_arc_targets:
    - "speaker"
    - "relationship"
  common_arc_patterns:
    - arc_id: "gentle_acceptance"
      phases: ["stability", "awareness", "sorrow", "acceptance"]
      notes: "悲しみを感じても、最終的には相手のために受け入れる。激しい抵抗より静かな受容"
    - arc_id: "hidden_understanding"
      phases: ["apparent_oblivion", "subtle_awareness", "revelation"]
      notes: "天然に見えて実は全て理解していたことが明かされる"
    - arc_id: "selfless_sacrifice"
      phases: ["normal", "crisis", "decision", "peaceful_acceptance"]
      notes: "他者のために自分を犠牲にすることを静かに選ぶ"