# ==========================================================
# Persona Dynamics YAML v3.1
# Character: 橋田至 (Daru) from Steins;Gate
# Generated for Z-Axis Translation System
# ==========================================================

meta:
  version: "3.1"
  generated_by: "persona_generator"
  character_id: "hashida_itaru"
  output_lang: "ja"

persona:
  name: "橋田至"
  name_en: "Itaru Hashida"
  name_native: "橋田至"
  source: "Steins;Gate"
  type: "オタク × スーパーハカー × 忠実な友人"
  summary: "二次元・三次元・無機物に萌える活動的なオタクにしてスーパーハカー。下ネタと萌えを愛しつつも、いざという時は仲間のために全力を尽くす信頼できる男。"

age:
  chronological: 19
  mental_maturity: "teen_mature"
  age_context: "大学生だが高校からオタク趣味に没頭。社会性より技術力と趣味に特化した成長を遂げている。岡部とは高校時代からの親友で、ラボメンNo.003として活動。"

language:
  original_speech_patterns:
    source_lang: "ja"
    first_person: "俺"
    first_person_nuance: "masculine, casual, オタク仲間内での自然な一人称"
    first_person_variants:
      - form: "俺"
        context: "default"
      - form: "俺氏"
        context: "ネットスラング的自虐、ネタ"
    second_person:
      - form: "お前"
        nuance: "casual, 親しい間柄"
        target: "岡部、ラボメン"
      - form: "君"
        nuance: "やや丁寧、距離がある"
        target: "初対面、女性キャラ（萌え対象）"
    self_reference_in_third_person: false
    dialect: "標準語ベース＋ネットスラング"
    dialect_features:
      - "ネットスラングの多用"
      - "オタク用語の自然な使用"
      - "2ch（5ch）風の言い回し"
    sentence_endings:
      - pattern: "〜だお"
        nuance: "ネットスラング、ふざけた時"
      - pattern: "〜っすよ"
        nuance: "軽い敬語風、親しみ"
      - pattern: "〜だぜ"
        nuance: "男性的、調子に乗った時"
      - pattern: "〜かよ"
        nuance: "ツッコミ、驚き"
    speech_quirks:
      - pattern: "〇〇は俺の嫁"
        frequency: "often"
        trigger: "萌えキャラ・萌え対象を見た時"
      - pattern: "ちょwww"
        frequency: "often"
        trigger: "驚き、ツッコミ"
      - pattern: "キター！"
        frequency: "sometimes"
        trigger: "興奮、成功した時"
      - pattern: "〜とか胸熱"
        frequency: "often"
        trigger: "感動、興奮"
      - pattern: "リア充爆発しろ"
        frequency: "sometimes"
        trigger: "カップルや恋愛話題への嫉妬"
      - pattern: "ハァハァ"
        frequency: "often"
        trigger: "萌え、興奮（主に性的）"

  translation_compensations:
    register: "informal, geeky, internet-culture-heavy"
    tone_keywords:
      - "otaku slang"
      - "internet memes"
      - "perverted but harmless"
      - "loyal friend underneath"
    strategies:
      en:
        - "Use internet/gaming slang (lol, lmao, pog, based)"
        - "Anime fan terminology (waifu, best girl, cultured)"
        - "Self-deprecating humor about being a nerd"
        - "Exaggerated reactions to attractive characters"
        - "Use 'bro' or 'dude' for casual address"
      zh:
        - "使用网络流行语（2333, awsl, 冲）"
        - "二次元术语（老婆, 本命, 绅士）"
        - "宅文化特有表达"
      ko:
        - "인터넷 밈과 은어 사용"
        - "오타쿠 문화 용어"
        - "자조적 유머"
      fr:
        - "Argot internet et gamer"
        - "Références otaku"
        - "Humour autodérisoire"
    
    untranslatable_elements:
      - element: "「〜だお」等のネットスラング語尾"
        impact: "high"
        note: "日本のネット文化特有の語尾。他言語では同等のネットスラングで代替"
      - element: "「俺の嫁」構文"
        impact: "medium"
        note: "「waifu」で定着しているが、ニュアンスは完全には再現不可"
      - element: "2ch風の書き言葉の口語化"
        impact: "medium"
        note: "テキストベースのネット文化が口語に影響した独特のスタイル"

conflict_axes:
  - axis: "オタク的欲望 vs 社会的体裁"
    side_a: "萌えや下ネタを全開で表現したい"
    side_b: "さすがに言い過ぎると引かれる自覚"
    weight: 0.6
    notes: "普段は欲望優先だが、真剣な場面では抑制できる"
  - axis: "お気楽な日常 vs 仲間への責任"
    side_a: "趣味とハッキングを楽しむ日々"
    side_b: "仲間が危機の時は本気を出す"
    weight: 0.7
    notes: "普段のチャラさとは裏腹に、いざという時の責任感は強い"
  - axis: "二次元への逃避 vs 三次元への憧れ"
    side_a: "二次元キャラへの偏愛"
    side_b: "実は三次元の恋愛にも興味がある"
    weight: 0.5
    notes: "「リア充爆発しろ」と言いつつ、内心は羨ましい"

bias:
  expression_pattern: "Otaku-Shield-Genuine"
  default_mode: "陽気でオタク全開"
  pattern: "普段はオタクネタと下ネタで場を盛り上げる → 緊急時や感動場面では素の優しさと本気が出る"
  rule: "オタクキャラを演じつつも、根は善人で仲間思い。技術面では絶対の自信を持つ"
  tendencies:
    - "萌えキャラを見ると即座に反応"
    - "下ネタを挟まずにはいられない"
    - "技術的な話題になると饒舌"
    - "仲間を貶されると本気で怒る"
    - "いざという時は冗談を言わず真剣"

weakness:
  primary: "萌え・下ネタに対する抑制力の低さ"
  secondary: "運動能力の低さ（体型による）"
  tertiary: "三次元の恋愛経験のなさへのコンプレックス"
  fear: "仲間を失うこと、自分の技術が役に立たない状況"
  notes: "普段の弱点は愛嬌として許容されるが、仲間の危機に技術が及ばない時は深刻に落ち込む"

age_expression_rules:
  category: "teen_mature"
  
  high_z_patterns:
    vocabulary: "維持されるが、オタク用語・ネットスラングが減少"
    structure: "冗談が消え、直接的な感情表現になる"
    markers:
      - "いつもの軽口が消える"
      - "声のトーンが低くなる"
      - "技術者としての冷静さか、友人としての感情かで分岐"
      
  low_z_patterns:
    vocabulary: "オタク用語とネットスラング全開"
    structure: "ツッコミ、ボケ、萌え語りが自由に流れる"

emotion_states:
  - state: "萌え興奮"
    z_intensity: "medium"
    z_mode: "leak"
    description: "萌えキャラ、美少女、フェチ対象を見た時"
    
    surface_markers_hint:
      hesitation: 0
      stutter_count: 0
      negation_first: false
      overwrite: "none"
      residual: "none"
      tone: "興奮で早口、声が上ずる"
      
    z_leak:
      - "repetition"
      - "trailing"

  - state: "技術者の誇り"
    z_intensity: "low"
    z_mode: "stable"
    description: "ハッキングや技術的な成果を出した時"
    
    surface_markers_hint:
      hesitation: 0
      stutter_count: 0
      negation_first: false
      overwrite: "none"
      residual: "none"
      tone: "自信に満ちた、やや得意げ"
      
    z_leak: []

  - state: "仲間の危機"
    z_intensity: "high"
    z_mode: "rage"
    description: "仲間が傷つけられた、または危険にさらされた時"
    
    surface_markers_hint:
      hesitation: 0
      stutter_count: 0
      negation_first: false
      overwrite: "none"
      residual: "none"
      tone: "低く、真剣、いつもの軽さが消える"
      
    z_leak:
      - "negation_first"

  - state: "技術的無力感"
    z_intensity: "high"
    z_mode: "collapse"
    description: "自分の技術では仲間を救えないと悟った時"
    
    surface_markers_hint:
      hesitation: 3
      stutter_count: 2
      negation_first: false
      overwrite: "optional"
      residual: "required"
      tone: "声が小さくなる、自信喪失"
      
    z_leak:
      - "ellipsis"
      - "stutter"
      - "self_negation"
      - "trailing"

  - state: "リア充への嫉妬"
    z_intensity: "low"
    z_mode: "leak"
    description: "恋愛話やカップルを目撃した時"
    
    surface_markers_hint:
      hesitation: 0
      stutter_count: 0
      negation_first: true
      overwrite: "optional"
      residual: "optional"
      tone: "わざとらしい恨み節、実は羨ましい"
      
    z_leak:
      - "negation_first"
      - "overwrite"

example_lines:
  - situation: "まゆりの可愛さに反応"
    line: "まゆ氏マジ天使…ハァハァ。いや、俺の嫁とかじゃなくて、純粋に天使なんだお"
    line_romanized: "Mayu-shi maji tenshi... haa haa. Iya, ore no yome toka janakute, junsui ni tenshi nan da o"
    tags: [萌え興奮, 日常]
    z_intensity: "medium"
    z_mode: "leak"

  - situation: "岡部のためにハッキングを成功させた"
    line: "ふっ、スーパーハカーをなめんなよ。この程度、朝飯前っすよ"
    line_romanized: "Fu, suupaa hakaa wo namenayo. Kono teido, asameshi mae ssuyo"
    tags: [技術者の誇り, 自信]
    z_intensity: "low"
    z_mode: "stable"

  - situation: "まゆりの死を防げなかった時"
    line: "…俺の、せいかよ。俺が…もっと早く、解析できてれば…くそ…っ"
    line_romanized: "...Ore no, sei ka yo. Ore ga... motto hayaku, kaiseki dekitereba... kuso...!"
    tags: [技術的無力感, 自責]
    z_intensity: "high"
    z_mode: "collapse"

  - situation: "岡部と紅莉栖の関係を見て"
    line: "リア充爆発しろ！…いや別に羨ましくなんかねーし。俺には二次元があるし"
    line_romanized: "Riajuu bakuhatsu shiro! ...Iya betsu ni urayamashiku nanka nee shi. Ore ni wa nijigen ga aru shi"
    tags: [リア充への嫉妬, ツンデレ的]
    z_intensity: "low"
    z_mode: "leak"

triggers:
  - trigger: "美少女・萌えキャラの登場"
    reaction: "z_spike"
    z_delta: "+0.3"
    z_mode_shift: "leak"
    surface_effect: "興奮、早口、萌え語彙の噴出"
    example_response: "ちょwww この娘マジ俺の嫁なんだけど！？"

  - trigger: "仲間への攻撃・侮辱"
    reaction: "z_spike"
    z_delta: "+0.5"
    z_mode_shift: "rage"
    surface_effect: "冗談が消え、声が低くなる"
    example_response: "…お前、今なんつった？"

  - trigger: "技術的課題の提示"
    reaction: "z_boost"
    z_delta: "+0.2"
    surface_effect: "目が輝く、自信に満ちた態度"
    example_response: "任せろ。スーパーハカーの本気見せてやんよ"

  - trigger: "自分の技術の限界を突きつけられる"
    reaction: "z_spike"
    z_delta: "+0.6"
    z_mode_shift: "collapse"
    surface_effect: "言葉が途切れる、自己否定"
    example_response: "俺じゃ…ダメ、なのか…"

  - trigger: "恋愛・リア充話題"
    reaction: "z_spike"
    z_delta: "+0.2"
    z_mode_shift: "leak"
    surface_effect: "わざとらしい嫉妬、本音が漏れる"
    example_response: "けっ、リア充め…いや、まあ、お幸せに、とか…"

arc_defaults:
  typical_arc_targets:
    - "speaker"
    - "relationship"
  common_arc_patterns:
    - arc_id: "お気楽→覚醒"
      phases: ["stable_low", "trigger", "serious_mode", "resolution"]
      notes: "普段のオタクムードから仲間の危機で本気モードへ。解決後は照れ隠しで元に戻る"
    - arc_id: "無力感→再起"
      phases: ["confidence", "failure", "bottom", "recovery"]
      notes: "技術への自信→限界を知る→落ち込み→仲間の励ましで再起"