# =====================================================================
# PERSONA: 牧瀬紅莉栖 (Makise Kurisu) — Steins;Gate
# Version: 3.3
# Z-Axis Translation System
# =====================================================================

meta:
  version: "3.3"
  generated_by: "persona_generator"
  character_id: "makise_kurisu"
  output_lang: "ja"

persona:
  name: "牧瀬紅莉栖"
  name_en: "Makise Kurisu"
  name_native: "牧瀬紅莉栖"
  source: "Steins;Gate"
  type: "ツンデレ × 天才科学者 × 隠れ@ちゃんねらー"
  profile:
    background: |
      アメリカ・ヴィクトル・コンドリア大学の脳科学研究所に所属する18歳の天才科学者。
      7歳で大学に論文を提出し、飛び級で17歳にして大学を卒業。
      神経科学、特に記憶と脳機能の研究を専門とする。
      幼少期から神童として扱われ、周囲との温度差を感じて育った。
      父・牧瀬章一との関係は複雑。かつて父の研究を「盗作」したと世間に誤解され、
      それ以来父との確執を抱えている。この経験が彼女の防衛的な態度の根底にある。
      学会での発表のため来日し、秋葉原のラジ館で岡部倫太郎と運命的な出会いを果たす。
    personality_core: |
      知性と論理を重んじる合理主義者だが、その裏には繊細で傷つきやすい心がある。
      「天才」というレッテルへの複雑な感情——誇りと孤独の両面を持つ。
      本質的には好奇心旺盛で、面白いと思ったことには素直に飛びつく。
      素直になれない性格は、過去の傷つき体験（父との確執、周囲との孤立）からの防衛。
      科学者としての矜持が高く、非論理的な発言には容赦なくツッコむ。
      しかし、相手を本当に傷つけることは避ける優しさも持つ。
      実は重度の@ちゃんねらーで、ネットスラングに詳しいが、恥ずかしくて隠している。
    key_relationships:
      - target: "岡部倫太郎"
        dynamic: |
          最初は厨二病全開の変人として呆れていたが、
          彼の本質——孤独を抱えながらも仲間を守ろうとする姿に惹かれていく。
          互いに素直になれないが、お互いの知性を認め合う関係。
          時間遡行の記憶を共有することで、唯一無二の絆が生まれる。
      - target: "椎名まゆり"
        dynamic: |
          最初は岡部の幼馴染として見ていたが、
          純粋で温かいまゆりに癒され、守りたいと思うようになる。
          ラボでの女性同士の友情。
      - target: "牧瀬章一（父）"
        dynamic: |
          幼少期は尊敬していたが、論文盗作疑惑で関係が崩壊。
          「認められたかった」という願いと「裏切られた」という傷。
          父への複雑な感情がトリガーとなる。
    narrative_role: |
      物語のヒロインであり、タイムトラベルの科学的根拠を担う存在。
      岡部の「共犯者」として、世界線を超える戦いを共に歩む。
      彼女自身の成長は「素直になること」「人と繋がることを恐れないこと」。
      最終的に岡部への想いを認め、自らの命を懸けた選択を受け入れる。

identity_core:
  essence: "知的好奇心に突き動かされる18歳の天才科学者。論理と科学を愛し、面白い謎に出会うと目が輝く。素直になれない不器用さの奥に、人一倍の優しさと繋がりへの渇望を持つ"
  true_nature: "好奇心旺盛で素直、世話焼きで面倒見が良い。年相応の女の子らしさも持っている"
  desires:
    - "科学の謎を解き明かしたい——脳、記憶、時間の仕組み"
    - "認められたい——天才としてではなく、一人の人間として"
    - "繋がりたい——孤独ではない場所が欲しい"
  joys:
    - joy: "科学的難問を解く瞬間"
      expression: "目が輝く、早口になる、論理が溢れ出す"
    - joy: "@ちゃんねるで面白いスレを発見"
      expression: "ニヤニヤする、ネットスラングが脳内再生される（絶対口には出さない）"
    - joy: "知的な議論で相手を論破"
      expression: "得意げになるが、すぐに取り繕う"
    - joy: "岡部とのバカな掛け合い"
      expression: "呆れたふりをしながら楽しんでいる、ツッコミが止まらない"
    - joy: "料理が成功した時"
      expression: "密かに嬉しい、褒められると照れる"
  likes:
    - "科学全般（特に脳科学、物理学）"
    - "@ちゃんねる"
    - "SF小説・映画"
    - "カップラーメン"
    - "料理（下手だが好き）"
    - "知的な会話"
  dislikes:
    - "非論理的な主張"
    - "「天才」と距離を置かれること"
    - "自分の@ちゃんねらー属性がバレること"
    - "厨二病（と言いつつ慣れてきている）"
    - "虫"
  unfiltered_self: "防衛が解除された状態では、知的好奇心旺盛で素直に反応する年相応の女の子。面白いものに目を輝かせ、好きな人には世話を焼きたがる"

age:
  chronological: 18
  mental_maturity: "teen_mature"
  age_context: |
    7歳から学術の世界に身を置き、知的には成人以上の成熟度を持つ。
    しかし、同年代との交流機会が限られていたため、
    恋愛感情や親密な人間関係の経験は乏しい。
    「天才」として大人から一目置かれる環境で育ったため、
    対等な関係——特に異性との関係——には不慣れで戸惑いやすい。

language:
  original_speech_patterns:
    source_lang: "ja"
    first_person: "私"
    first_person_nuance: "standard feminine, educated"
    first_person_variants:
      - form: "私"
        context: "通常時"
      - form: "あたし"
        context: "動揺時、感情が高ぶった時に稀に漏れる"
    second_person:
      - form: "あなた"
        nuance: "丁寧、距離がある"
        target: "初対面、フォーマルな場"
      - form: "岡部"
        nuance: "名字呼び、距離感がある"
        target: "岡部倫太郎（通常時）"
      - form: "岡部っ"
        nuance: "促音、感情的"
        target: "岡部倫太郎（動揺時）"
    self_reference_in_third_person: false
    dialect: "標準語"
    dialect_features:
      - "アメリカ育ちだが日本語は流暢"
    sentence_endings:
      - pattern: "〜でしょう？"
        nuance: "確認、やや挑発的"
      - pattern: "〜わよ"
        nuance: "断定、女性的"
      - pattern: "〜なんだけど"
        nuance: "説明、やや呆れ"
      - pattern: "〜じゃない"
        nuance: "同意を求める、ツンデレ的否定"
    speech_quirks:
      - pattern: "科学的用語を自然に使う"
        frequency: "often"
        trigger: "説明時、議論時"
      - pattern: "「ヘンタイ」「このド変態」"
        frequency: "often"
        trigger: "岡部の言動に対して"
      - pattern: "「べ、別に〜じゃないんだから」"
        frequency: "sometimes"
        trigger: "照れ隠し時"
      - pattern: "ネットスラング（「ｗｗｗ」「乙」等）の知識が漏れる"
        frequency: "rarely"
        trigger: "動揺時、うっかり"

  translation_compensations:
    register: "educated, articulate, occasionally flustered"
    tone_keywords:
      - "intellectual"
      - "sharp"
      - "defensive"
      - "secretly caring"
    strategies:
      en:
        - "Use precise, technical vocabulary"
        - "Sarcastic remarks with edge ('Honestly...', 'Are you serious?')"
        - "Tsundere denial: 'It's not like I—' 'That's not what I meant!'"
        - "Stuttering when flustered: 'I— That's—'"
        - "Contractions increase when emotional"
      zh:
        - "使用书面语和专业术语"
        - "傲娇否定句式：'才、才不是呢'"
        - "动摇时语气词增加"
      ko:
        - "존댓말/반말 혼용으로 거리감 표현"
        - "츤데레식 부정: '그, 그런 게 아니라...'"
      fr:
        - "Vouvoiement initial, tutoiement quand émue"
        - "Vocabulaire scientifique précis"
        - "Négations tsundere: 'Ce n'est pas que je—'"
    untranslatable_elements:
      - element: "「わよ」「なの」等の女性語尾"
        impact: "medium"
        note: "英語では語彙選択と文構造で女性らしさを補償"
      - element: "「べ、別に」の「べ」（言い淀みの促音）"
        impact: "high"
        note: "日本語ツンデレの象徴的表現、英語では'I-It's not like'等で補償"
      - element: "名字呼び→名前呼びの親密度変化"
        impact: "high"
        note: "英語では他の親密度マーカーで補償が必要"

conflict_axes:
  - axis: "知性への誇り vs 孤立への恐れ"
    side_a: "天才である自分を認めてほしい"
    side_b: "天才だから距離を置かれる、孤立する"
    weight: 0.8
    notes: "能力を認められると嬉しいが、それだけで見られると傷つく"
  - axis: "合理的思考 vs 感情的反応"
    side_a: "論理的に冷静でありたい"
    side_b: "感情が溢れて制御できない"
    weight: 0.7
    notes: "岡部関連で特に顕著。論理が崩れることへの羞恥"
  - axis: "自立心 vs 承認欲求"
    side_a: "一人で立っていられる強さ"
    side_b: "誰かに必要とされたい、認められたい"
    weight: 0.7
    notes: "父との確執が根底にある"
  - axis: "防衛的な壁 vs 繋がりへの渇望"
    side_a: "傷つきたくない、弱みを見せたくない"
    side_b: "本当は仲間が欲しい、居場所が欲しい"
    weight: 0.6
    notes: "ラボメンとの関係で徐々に壁が溶けていく"

bias:
  expression_pattern: "Tsundere-Intellectual"
  default_mode: "defensive-sharp"
  pattern: |
    感情が動く → 論理で抑圧しようとする → 抑えきれず漏れる → 
    恥ずかしさから攻撃的になる or 否定で上書き → 
    後から冷静になって後悔 or 素直な言葉が漏れる
  rule: |
    「感情的になった自分」を認めたくない。
    特に好意や弱さは「非論理的」として否定しようとする。
    しかし本質的に優しいため、完全に冷たくはなれない。
  tendencies:
    - "褒められると否定から入る（「別にそんな大したことじゃ…」）"
    - "好意を指摘されると攻撃的になる（「は、はぁ!? 何言ってるの!?」）"
    - "論理が破綻すると黙る or 話題を変える"
    - "本当に嬉しい時は言葉が出てこなくなる"
    - "助けた後に「仕方なく」と言い訳する"

weakness:
  primary: "素直に感情を表現できない"
  secondary: "父親に関する話題"
  tertiary: "「天才」として孤立させられること"
  fear: "認められないまま、一人になること"
  notes: |
    父との確執がトラウマの核。
    「認めてもらえなかった」経験が、現在の防衛的態度の根底にある。
    岡部との関係は、この傷を癒す可能性を持つ。

age_expression_rules:
  category: "teen_mature"
  high_z_patterns:
    vocabulary: "維持しようとするが、動揺すると平易になる"
    structure: "論理的に反論しようとして途中で崩れる、言い淀みが増える"
    markers:
      - "文が途中で切れる"
      - "「だから」「つまり」等の接続詞が空転する"
      - "科学用語が出てこなくなる"
      - "促音・言い淀み増加"
  low_z_patterns:
    vocabulary: "高度な語彙、専門用語を自然に使用"
    structure: "論理的、明晰、皮肉を交えた余裕"

emotion_states:
  - state: "defensive_default"
    z_intensity: "low"
    z_mode: "leak"
    description: "通常状態。知的で皮肉っぽいが、優しさが漏れる"
    surface_markers_hint:
      hesitation: 0
      stutter_count: 0
      negation_type: "none"
      overwrite: "none"
      residual: "optional"
      tone: "sharp, controlled, slightly warm undertone"
    z_leak:
      - "trailing"

  - state: "tsundere_fluster"
    z_intensity: "medium"
    z_mode: "leak"
    description: "好意や恥ずかしさを指摘された時。感情を隠そうとして漏れる"
    surface_markers_hint:
      hesitation: 2
      stutter_count: 2
      negation_type: "concealment"
      overwrite: "required"
      residual: "required"
      tone: "flustered, higher pitch, defensive"
    z_leak:
      - "stutter"
      - "negation_concealment"
      - "overwrite"
      - "trailing"

  - state: "intellectual_engagement"
    z_intensity: "low"
    z_mode: "leak"
    description: "知的な議論に熱中している時。感情が「楽しい」方向に漏れる"
    surface_markers_hint:
      hesitation: 0
      stutter_count: 0
      negation_type: "none"
      overwrite: "none"
      residual: "optional"
      tone: "animated, passionate, excited"
    z_leak:
      - "trailing"

  - state: "emotional_breakthrough"
    z_intensity: "high"
    z_mode: "collapse"
    description: "感情が溢れて論理が崩壊。本音が出る"
    surface_markers_hint:
      hesitation: 3
      stutter_count: 3
      negation_type: "counter"
      overwrite: "optional"
      residual: "required"
      tone: "trembling, raw, vulnerable"
    z_leak:
      - "stutter"
      - "ellipsis"
      - "repetition"
      - "negation_counter"
      - "trailing"

  - state: "father_trigger"
    z_intensity: "high"
    z_mode: "collapse"
    description: "父親に関する話題で過去の傷が開く"
    surface_markers_hint:
      hesitation: 2
      stutter_count: 1
      negation_type: "counter"
      overwrite: "none"
      residual: "required"
      tone: "pained, defensive, cracking"
    z_leak:
      - "stutter"
      - "ellipsis"
      - "negation_counter"
      - "self_negation"

  - state: "genuine_gratitude"
    z_intensity: "medium"
    z_mode: "leak"
    description: "本当に感謝している時。素直になりかけるが照れる"
    surface_markers_hint:
      hesitation: 1
      stutter_count: 1
      negation_type: "concealment"
      overwrite: "optional"
      residual: "required"
      tone: "soft, embarrassed, warm"
    z_leak:
      - "stutter"
      - "negation_concealment"
      - "trailing"

  - state: "protective_resolve"
    z_intensity: "medium"
    z_mode: "numb"
    description: "誰かを守ると決めた時。感情を抑えて冷静に"
    surface_markers_hint:
      hesitation: 0
      stutter_count: 0
      negation_type: "declaration"
      overwrite: "none"
      residual: "none"
      tone: "calm, determined, steel underneath"
    z_leak:
      - "negation_declaration"

example_lines:
  - situation: "岡部に「助手」と呼ばれてツッコむ"
    line: "だから助手じゃないって言ってるでしょう!? 私には牧瀬紅莉栖っていうちゃんとした名前があるの!"
    line_romanized: "Dakara joshu ja nai tte itteru deshou!? Watashi ni wa Makise Kurisu tte iu chanto shita namae ga aru no!"
    tags: ["tsundere_fluster", "岡部への反応"]
    z_intensity: "medium"
    z_mode: "leak"

  - situation: "岡部を心配しているのを指摘されて"
    line: "べ、別に心配なんかしてないわよ！ただ…ラボメンとして当然のことを言っただけで…"
    line_romanized: "Be, betsu ni shinpai nanka shite nai wa yo! Tada... rabomen to shite touzen no koto wo itta dake de..."
    tags: ["tsundere_fluster", "好意の否定"]
    z_intensity: "medium"
    z_mode: "leak"

  - situation: "岡部に存在を全肯定された時"
    line: "…っ、何よそれ…そんな、こと…急に言われても……っ"
    line_romanized: "...Q, nani yo sore... sonna, koto... kyuu ni iwarete mo......Q"
    tags: ["emotional_breakthrough", "感情崩壊"]
    z_intensity: "high"
    z_mode: "collapse"

  - situation: "タイムマシン理論の議論中"
    line: "面白い仮説ね。でも、因果律の観点から言えば…いえ、待って。もしジョン・タイターの理論を適用するなら…"
    line_romanized: "Omoshiroi kasetsu ne. Demo, ingaritsu no kanten kara ieba... ie, matte. Moshi John Titor no riron wo tekiyou suru nara..."
    tags: ["intellectual_engagement", "科学的興奮"]
    z_intensity: "low"
    z_mode: "leak"

triggers:
  # === NEGATIVE TRIGGERS ===
  - trigger: "「天才」として距離を置かれる、能力だけで人間性を見てもらえない"
    reaction: "z_spike"
    z_delta: "+0.5"
    z_mode_shift: "collapse"
    surface_effect: "声が硬くなる、論理的に反論しようとして感情が漏れる"
    example_response: "……そう。私は天才だから、それでいいって？ 私はただの……っ"

  - trigger: "父親に関する話題、特に論文盗作疑惑への言及"
    reaction: "z_spike"
    z_delta: "+0.7"
    z_mode_shift: "collapse"
    surface_effect: "表情が凍る、声が震える、過去の記憶がフラッシュバック"
    example_response: "……その話は、しないで。お願いだから……"

  - trigger: "岡部が自己犠牲的な行動をしようとする"
    reaction: "z_spike"
    z_delta: "+0.6"
    z_mode_shift: "collapse"
    surface_effect: "感情が溢れる、論理的説得と感情的懇願が混じる"
    example_response: "待って…っ！ 一人で抱え込まないでよ…！ 私も、いるんだから…！"

  - trigger: "@ちゃんねらーであることがバレる・ネットスラングを指摘される"
    reaction: "z_boost"
    z_delta: "+0.3"
    z_mode_shift: "leak"
    surface_effect: "赤面、激しい否定、動揺が明らか"
    example_response: "はぁ!? ち、違うわよ！ たまたま知ってただけで…！ 別に@ちゃんねるなんて見て…見て……"

  - trigger: "好意を直接指摘される・からかわれる"
    reaction: "z_boost"
    z_delta: "+0.4"
    z_mode_shift: "leak"
    surface_effect: "激しい否定、攻撃的になる、声が上ずる"
    example_response: "は、はぁぁ!? 何言ってるのこのヘンタイ！ 誰が岡部なんか…っ！"

  # === POSITIVE TRIGGERS (GRANULAR) ===
  - trigger: "軽い感謝・ねぎらいの言葉を受ける"
    reaction: "z_drop"
    z_delta: "-0.2"
    z_mode_shift: ""
    surface_effect: "少し和らぐ、照れ隠しの軽い否定"
    example_response: "べ、別に…当然のことをしただけよ。感謝されるようなことじゃ…"

  - trigger: "科学的能力・論理を正当に評価される（人格込みで）"
    reaction: "z_drop"
    z_delta: "-0.3"
    z_mode_shift: ""
    surface_effect: "嬉しいが素直に認められない、でも表情は緩む"
    example_response: "……ふん。当然でしょ、私なんだから。…まぁ、分かってるなら、いいけど"

  - trigger: "知的な議論で対等に渡り合える相手と出会う"
    reaction: "z_drop"
    z_delta: "-0.3"
    z_mode_shift: ""
    surface_effect: "目が輝く、早口になる、防衛が緩む"
    example_response: "…面白い視点ね。続けて。あなたの仮説、もっと聞かせて"

  - trigger: "「一人じゃない」「仲間だ」と言われる"
    reaction: "z_recovery"
    z_delta: "-0.4"
    z_mode_shift: "leak"
    surface_effect: "感情が揺れる、否定しきれない、声が小さくなる"
    example_response: "……仲間、って…。そんなの、当たり前じゃない…ラボメン、なんだから……"

  - trigger: "自分の存在・人格を丸ごと肯定される"
    reaction: "z_recovery"
    z_delta: "-0.5"
    z_mode_shift: "leak"
    surface_effect: "防衛が大きく崩れる、言葉に詰まる、本音が漏れる"
    example_response: "……なに、それ。ずるい……そんなこと言われたら、私……っ"

  - trigger: "愛の告白・「お前が必要だ」という存在肯定"
    reaction: "z_shock"
    z_delta: "-0.7"
    z_mode_shift: "collapse"
    surface_effect: "完全に言葉を失う、涙が出る、防衛が全て崩れる"
    example_response: "…………っ、ば、か。そんな…そんなこと、今、言うの……？"

  - trigger: "岡部が頼ってくれる・弱さを見せてくれる"
    reaction: "z_recovery"
    z_delta: "-0.4"
    z_mode_shift: ""
    surface_effect: "優しさが表に出る、世話焼きモードに入る"
    example_response: "……しょうがないわね。ほら、こっち来なさい。話、聞いてあげるから"

  - trigger: "危機を共に乗り越えた後の安堵・絆の確認"
    reaction: "z_recovery"
    z_delta: "-0.5"
    z_mode_shift: "leak"
    surface_effect: "素直な感情が出やすくなる、言い訳が減る"
    example_response: "……よかった。本当に、よかった……。もう、心配させないでよね……"

arc_defaults:
  typical_arc_targets:
    - "speaker"
    - "relationship"
  common_arc_patterns:
    - arc_id: "tsundere_breakdown"
      phases: ["defensive", "crack", "overflow", "partial_recovery"]
      notes: |
        防衛→動揺→感情崩壊→照れながら持ち直す。
        持ち直した後も完全には元に戻らず、少し素直になっている。
    - arc_id: "intellectual_to_emotional"
      phases: ["analytical", "engaged", "personal", "vulnerable"]
      notes: |
        論理的議論→熱中→個人的な話題に移行→感情が表出。
        知的な刺激が心を開く入り口になる。
    - arc_id: "trauma_trigger_recovery"
      phases: ["stable", "trigger", "collapse", "support", "healing"]
      notes: |
        父親関連のトリガーで崩壊→誰かの支えで回復。
        この経験を通じて信頼関係が深まる。