#!/usr/bin/env python3
"""
Episode Generator v1.1
======================
キャラクター名から Episode Memory YAML を生成（Web 検索版）。
原作テキストがある場合は episode_extractor.py を使う。

  persona_generator → 「この人は誰か」
  episode_generator → 「この人は何を経験したか」

Two-pass:
  Pass 1 (Research): web_search で原作のエピソード・台詞を調べる
  Pass 2 (Generate): 調査結果をもとに YAML を構造化する

v1.1 Changes:
- ライブラリ化: generate_episodes() を UI / pipeline から直接呼べる関数に
- LLM 呼び出しを core.llm に統一（BYOK・モデル登録表）。既定モデルを claude-opus-5-5 に
- --thinking N（budget）→ --effort（low〜max）。--thinking は互換のため残し、指定時は high 扱い
- YAML 抽出・修復を core.yamlio に移動

Usage:
  python episode_generator.py --name "椎名まゆり" --source "Steins;Gate" \\
    --desc "ラボメンNo.002、岡部倫太郎の幼馴染" --effort high
  python episode_generator.py --name "椎名まゆり" --source "Steins;Gate 0" --sequel \\
    --persona personas/椎名まゆり_v33.yaml
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

import yaml

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from divergence_z.core import (EFFORTS, LLM, Keys, LLMResult, Progress, clean_yaml_output,
                               print_progress, resolve_progress)

# ============================================================
# Configuration
# ============================================================

DEFAULT_MODEL = os.getenv("EPISODE_GENERATOR_MODEL", "claude-opus-5-5")
DEFAULT_EFFORT = "high"

SUPPORTED_LANGUAGES = {
    "ja": "Japanese (日本語)",
    "en": "English",
    "zh": "Chinese (中文)",
    "ko": "Korean (한국어)",
    "fr": "French (Français)",
    "de": "German (Deutsch)",
    "es": "Spanish (Español)",
}

# ============================================================
# Episode YAML Schema Definition
# ============================================================

EPISODE_SCHEMA = """
# ===================================================================
# Episode Memory YAML v1.0
# Character: {name}
# Source: {source}
# Generated by: episode_generator
# ===================================================================

meta:
  version: "1.0"
  generated_by: "episode_generator"
  character_id: "{character_id}"  # same as persona YAML
  persona_file: "{persona_file}"  # reference to companion persona YAML
  source: "{source}"
  
# Timeline / world-line organization
# For multi-timeline works (Steins;Gate, Re:Zero, etc.), group by timeline
timelines:
  - timeline_id: "main"
    label: "Main timeline / route"
    episodes: []

# Each episode follows this structure:
# - episode_id: "unique_snake_case_id"
#   timeline: "which timeline this occurs in"
#   chronological_order: 1  # integer for sorting within timeline
#   title: "Short descriptive title"
#   source_episode: "Episode 12" or "Chapter 5" or "Route: True End"
#   
#   summary: |
#     What happened in this episode. Focus on the CHARACTER's experience,
#     not just plot events. What did they see, feel, learn, lose?
#   
#   participants:
#     - name: "Other character"
#       role: "ally / antagonist / catalyst / witness"
#   
#   emotional_impact: "low / medium / high / critical"
#   emotional_detail: |
#     How this episode affected the character emotionally.
#     What changed inside them? What did they carry forward?
#   
#   canonical_quotes:
#     - quote: "Actual dialogue from this scene"
#       context: "Who they're speaking to, what's happening"
#       z_intensity: "low / medium / high"
#       z_mode: "stable / concern / grief / nurture / resolve / release"
#   
#   z_relevance: |
#     How this episode affects translation decisions.
#     What must a translator know about this episode to correctly
#     translate dialogue that references or is shaped by it?
#   
#   character_state_change:
#     before: "Character's state before this episode"
#     after: "Character's state after this episode"  
#     permanent: true/false  # Does this change persist?
#   
#   tags: ["origin_story", "loss", "growth", "relationship", "turning_point"]

# Cross-episode arcs that span multiple episodes
arcs:
  - arc_id: "unique_arc_id"
    title: "Arc title"
    episodes: ["ep_id_1", "ep_id_2", "ep_id_3"]
    theme: "What this arc is about"
    character_growth: |
      How the character changes across this arc.
    z_translation_note: |
      What translators need to know about this arc to handle
      dialogue that references or builds on it.
"""

# ============================================================
# Prompt Builders
# ============================================================

def build_system_prompt(output_lang: str) -> str:
    """Build system prompt for episode YAML generation."""
    lang_name = SUPPORTED_LANGUAGES.get(output_lang, output_lang)
    
    return f"""You are an expert character analyst and narrative researcher specializing in 
fictional character episode documentation for the Divergence-Z translation system.

Your task is to generate an Episode Memory YAML file that captures a character's 
key experiences, memories, and narrative events. This file complements the persona YAML 
(which describes WHO a character is) by documenting WHAT they experienced.

## WHY EPISODE MEMORY MATTERS FOR TRANSLATION

When translating character dialogue, the translator needs to know not just HOW 
the character speaks (persona), but WHAT shaped them (episodes). 

Example: When Mayuri says "I know how hard you've been trying, Okarin," 
a translator needs to know:
- She doesn't have DIRECT memory of the time loops (persona knowledge)
- But she has INTUITIVE understanding from fragments (episode knowledge)
- This line's weight comes from Episode context, not just personality

Without episode context, a translator might render this as simple encouragement.
With episode context, they know it carries the weight of hundreds of unseen deaths.

## OUTPUT FORMAT

Generate a valid YAML file following the Episode Memory YAML v1.0 schema.
All descriptions should be in {lang_name}.
Canonical quotes MUST be in the character's original language.

## CRITICAL RULES

1. **CANONICAL ONLY**: Every episode must be from the actual source material.
   Do NOT invent episodes. If unsure, mark with confidence level.
   
2. **CANONICAL QUOTES**: canonical_quotes must be actual dialogue from the work.
   "Sounds like something they'd say" is NOT acceptable.
   If you cannot find the exact quote, describe the scene without fabricating dialogue.

3. **CHARACTER-CENTRIC**: Describe events from the CHARACTER's perspective.
   Not "Okabe time-leaped" but "Mayuri died again without knowing why."

4. **Z-RELEVANCE**: Every episode must include z_relevance explaining
   how this episode affects translation decisions.

5. **EMOTIONAL TRUTH**: Focus on emotional impact, not just plot mechanics.
   What did this episode FEEL like for the character?

{f'''## CHARACTER RESEARCH CONTEXT
The following research was gathered about this character.
USE this context to ensure episode accuracy and canonical quote fidelity.
''' if True else ''}"""


def build_user_prompt(name: str, source: str, description: str, 
                      output_lang: str, search_context: str = "",
                      persona_context: str = "",
                      max_episodes: int = 20,
                      include_sequel: bool = False) -> str:
    """Build user prompt for episode generation."""
    lang_name = SUPPORTED_LANGUAGES.get(output_lang, output_lang)
    
    prompt = f"""Generate an Episode Memory YAML v1.0 for:

Character: {name}
Source: {source}
Description: {description}
Output Language: {lang_name}
Maximum Episodes: {max_episodes}
{"Include sequel/spinoff episodes: Yes" if include_sequel else "Focus on main work only"}
"""
    
    if persona_context:
        prompt += f"""
## Companion Persona YAML (for reference)
The following persona YAML exists for this character. Use it to understand
their personality, conflicts, and speech patterns. Episodes should be
consistent with the persona's conflict_axes and triggers.

{persona_context}
"""
    
    if search_context:
        prompt += f"""
## Research Context (from web search)
USE this research to ensure episode accuracy and canonical quote fidelity.
Prioritize information from this research over your training data.

{search_context}
"""
    
    prompt += f"""
## EPISODE SELECTION CRITERIA

Select the most impactful episodes by these priorities:
1. **Origin episodes**: Events that shaped the character's core identity
2. **Relationship milestones**: Key moments with important characters  
3. **Turning points**: Where the character's worldview or behavior changed
4. **Trauma/Loss**: Events that left lasting emotional marks
5. **Growth moments**: Where the character overcame limitations
6. **Iconic scenes**: Widely recognized, frequently referenced moments

## EPISODE STRUCTURE

For each episode, include:
- episode_id (unique snake_case)
- timeline (for multi-timeline works)
- chronological_order (integer for sorting)
- title (short, descriptive)
- source_episode (episode/chapter/route number)
- summary (character-centric description)
- participants (who else is involved)
- emotional_impact (low/medium/high/critical)
- emotional_detail (how it affected them)
- canonical_quotes (ACTUAL dialogue, with context and z_mode)
- z_relevance (translation implications)
- character_state_change (before/after/permanent)
- tags

## CANONICAL QUOTES: WHY ACCURACY MATTERS

canonical_quotes serve as GROUND TRUTH for translation.
When a translator encounters dialogue that echoes or references these moments,
they need the original wording to maintain consistency.

Without accurate quotes: translator produces "plausible fabrication"
With accurate quotes: translator produces text that IS the character

If you cannot verify exact wording, use this format:
  - quote: "[unverified] Approximate: オカリン、もういいんだよ"
    context: "Scene where Mayuri comforts Okabe"

## ARC STRUCTURE

After listing episodes, identify 2-5 cross-episode arcs that span 
multiple episodes. These help translators understand how dialogue
in later scenes carries weight from earlier events.

Each arc MUST use these exact key names:
  - arc_id: "unique_id"
  - title: "Arc title"
  - episodes: ["ep_id_1", "ep_id_2"]   # KEY MUST BE "episodes", NOT "episodes_included"
  - theme: "description"

Also ensure meta section uses "version" (not "schema_version"):
  meta:
    version: "1.0"   # NOT schema_version

Output ONLY valid YAML. No explanation text before or after.

## YAML QUOTING RULES (CRITICAL)

When a YAML value contains double quotes, you MUST wrap the entire value in single quotes:

WRONG (will break YAML parser):
  translation: "From zero"を維持、対比を意識

CORRECT:
  translation: '"From zero"を維持、対比を意識'

ALSO CORRECT:
  translation: |
    "From zero"を維持、対比を意識

This applies to ALL fields, not just translation. Any value containing " must be
either single-quoted or use block scalar (|)."""
    
    return prompt

# ============================================================
# Two-pass: research → generate
# ============================================================

RESEARCH_SYSTEM = ("You are a research assistant. You MUST use the web_search tool for EVERY request. "
                   "NEVER answer from your own knowledge alone. Always search first, then summarize "
                   "findings. Perform at least 2 separate searches before answering.")


def build_research_prompt(name: str, source: str, description: str,
                          include_sequel: bool = False) -> str:
    """Pass 1 の調査プロンプト（なぜ検索が必要かを説明する reason-driven 形式）"""
    sequel_instruction = ""
    if include_sequel:
        sequel_instruction = f"\n4. Search: \"{name} sequel spinoff episodes\" — for episodes from related works"
    
    return f"""You are a research assistant. Your ONLY job is to use web_search to find information.
Do NOT answer from memory. You MUST search first, then report what you found.

Character: {name}
Source: {source}
Description: {description}

WHY SEARCH IS ESSENTIAL FOR EPISODE MEMORY:
Episode Memory files contain canonical_quotes — actual dialogue from specific scenes.
These quotes serve as GROUND TRUTH for a translation system.

The difference between searched and unsearched episode data:
- Without search: "Episode 12: Mayuri probably dies" (vague, maybe wrong episode number)
- With search: "Episode 12 'Dogma in Ergosphere': Mayuri is hit by a train at 7:42 PM" (verified)

LLM memory is especially unreliable for:
- Exact episode numbers and titles
- Which specific scene a quote comes from  
- Chronological order of events across timelines
- Exact wording of dialogue (often paraphrased in training data)

These details DIRECTLY impact translation quality. A translator working from
wrong episode context will misread the weight of every line.

EXECUTE THESE SEARCHES NOW:
1. "{name} {source} wiki plot episodes" — story events and episode numbers
2. "{name} {source} 名言 名シーン セリフ" — iconic quotes with scene context
3. "{name} {source} character arc timeline" — character development and changes{sequel_instruction}

After ALL searches are complete, compile findings:

## Key Episodes / Scenes
(list major events with VERIFIED episode numbers/chapter numbers)

## Iconic Quotes / Dialogue  
(actual lines found in search results, with scene context)
CRITICAL: Only include quotes you found in search results.
Mark uncertain ones as [approximate].

## Character Arc Summary
(how the character changes, with timeline/episode markers)

## Relationship Milestones
(key moments with other characters, episode-specific)

## Timeline / Route Information
(for multi-timeline works: which events in which timeline/route)

Only include information you actually found in search results."""


def research_episodes(name: str, source: str, description: str, *, llm: LLM,
                      model: str = DEFAULT_MODEL, include_sequel: bool = False,
                      progress: Optional[Progress] = None) -> LLMResult:
    """Pass 1: web_search で原作のエピソード・台詞を調べる"""
    resolve_progress(progress)("   📖 Pass 1: Researching character episodes via web search...")
    result = llm.complete(RESEARCH_SYSTEM,
                          build_research_prompt(name, source, description, include_sequel),
                          model=model, effort="low", max_output_tokens=10000,
                          web_search=True, max_searches=8)
    if result.searches == 0:
        resolve_progress(progress)("   ⚠️  Model did not use web search in research pass")
    return result


@dataclass
class EpisodeResult:
    character: str
    yaml_text: str
    valid: bool
    issues: List[str] = field(default_factory=list)
    episode_count: int = 0
    research: Optional[LLMResult] = None
    llm: Optional[LLMResult] = None


def count_episodes(yaml_text: str) -> int:
    try:
        data = yaml.safe_load(yaml_text) or {}
    except yaml.YAMLError:
        return 0
    if not isinstance(data, dict):
        return 0
    n = sum(len(tl.get("episodes") or []) for tl in data.get("timelines") or []
            if isinstance(tl, dict))
    return n + len(data.get("episodes") or [])


def generate_episodes(name: str, source: str, description: str = "", *, llm: LLM,
                      model: str = DEFAULT_MODEL, effort: Optional[str] = DEFAULT_EFFORT,
                      output_lang: str = "ja", web_search: bool = True,
                      include_sequel: bool = False, max_episodes: int = 20,
                      persona_text: str = "", rate_limit_wait: int = 0,
                      max_output_tokens: int = 32000,
                      progress: Optional[Progress] = None) -> EpisodeResult:
    """キャラクター名から Episode Memory YAML を生成（web_search=False なら LLM の知識のみ）"""
    report = resolve_progress(progress)
    report(f"📖 Generating Episode Memory for: {name} ({source})")

    research = None
    if web_search:
        research = research_episodes(name, source, description, llm=llm, model=model,
                                     include_sequel=include_sequel, progress=progress)
        if rate_limit_wait:
            report(f"   ⏳ Waiting {rate_limit_wait}s for rate limit reset...")
            time.sleep(rate_limit_wait)
        report("   📝 Pass 2: Generating Episode Memory YAML...")

    result = llm.complete(
        build_system_prompt(output_lang),
        build_user_prompt(name, source, description, output_lang,
                          search_context=research.text if research else "",
                          persona_context=persona_text, max_episodes=max_episodes,
                          include_sequel=include_sequel),
        model=model, effort=effort, max_output_tokens=max_output_tokens)
    yaml_text = clean_yaml_output(result.text, progress=report)
    valid, issues = validate_episode_yaml(yaml_text)
    return EpisodeResult(name, yaml_text, valid, issues, count_episodes(yaml_text), research, result)


# ============================================================
# Validation
# ============================================================

# ============================================================
# Validation
# ============================================================

def validate_episode_yaml(yaml_content: str) -> tuple:
    """Validate Episode Memory YAML structure.
    
    Returns:
        (is_valid: bool, issues: list[str])
    """
    issues = []
    
    # Try to parse YAML
    try:
        data = yaml.safe_load(yaml_content)
    except yaml.YAMLError as e:
        return False, [f"YAML parse error: {e}"]
    
    if not isinstance(data, dict):
        return False, ["Root must be a dict"]
    
    # Check meta (accept both "version" and "schema_version")
    if "meta" not in data:
        issues.append("Missing 'meta' section")
    else:
        meta = data["meta"]
        if "version" not in meta and "schema_version" not in meta:
            issues.append("Missing meta.version (or meta.schema_version)")
        if "character_id" not in meta:
            issues.append("Missing meta.character_id")
    
    # Check for episodes (can be in timelines or top-level)
    has_episodes = False
    episode_count = 0
    
    if "timelines" in data:
        for tl in data["timelines"]:
            if not isinstance(tl, dict):
                issues.append(f"Timeline entry is not a dict (got {type(tl).__name__})")
                continue
            if "episodes" in tl and tl["episodes"]:
                has_episodes = True
                episode_count += len(tl["episodes"])
                
                for ep in tl["episodes"]:
                    if not isinstance(ep, dict):
                        issues.append(f"Episode entry is not a dict (got {type(ep).__name__})")
                        continue
                    ep_id = ep.get("episode_id", "unknown")
                    
                    # Check required fields
                    if "episode_id" not in ep:
                        issues.append(f"Episode missing episode_id")
                    if "summary" not in ep:
                        issues.append(f"Episode '{ep_id}' missing summary")
                    if "emotional_impact" not in ep:
                        issues.append(f"Episode '{ep_id}' missing emotional_impact")
                    if "z_relevance" not in ep:
                        issues.append(f"Episode '{ep_id}' missing z_relevance")
                    
                    # Check canonical quotes format
                    if "canonical_quotes" in ep:
                        for q in ep["canonical_quotes"]:
                            if not isinstance(q, dict):
                                issues.append(f"Episode '{ep_id}': quote is not a dict")
                                continue
                            if "quote" not in q:
                                issues.append(f"Episode '{ep_id}': quote missing 'quote' field")
    
    if "episodes" in data and data["episodes"]:
        has_episodes = True
        episode_count += len(data["episodes"])
    
    if not has_episodes:
        issues.append("No episodes found (check timelines[].episodes)")
    
    # Check arcs (accept both "episodes" and "episodes_included")
    if "arcs" in data and data["arcs"]:
        for arc in data["arcs"]:
            if not isinstance(arc, dict):
                issues.append(f"Arc entry is not a dict (got {type(arc).__name__}: {str(arc)[:50]})")
                continue
            if "arc_id" not in arc:
                issues.append("Arc missing arc_id")
            if "episodes" not in arc and "episodes_included" not in arc:
                issues.append(f"Arc '{arc.get('arc_id', 'unknown')}' missing episodes list (expected 'episodes' or 'episodes_included')")
    
    is_valid = len(issues) == 0
    return is_valid, issues

# ============================================================
# CLI
# ============================================================

def save_episodes(yaml_text: str, output_path: str, valid_issues: List[str]) -> tuple:
    """保存。パースエラーなら _BROKEN.yaml に退避して (path, False) を返す"""
    if any("YAML parse error" in issue for issue in valid_issues):
        output_path = output_path.replace(".yaml", "_BROKEN.yaml")
        ok = False
    else:
        ok = True
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(yaml_text, encoding="utf-8")
    return output_path, ok


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Episode Generator v1.1 — Generate Episode Memory YAML (web search)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--name", required=True, help="Character name")
    parser.add_argument("--source", required=True, help="Source work")
    parser.add_argument("--desc", default="", help="Brief character description")
    parser.add_argument("--lang", default="ja", choices=SUPPORTED_LANGUAGES.keys())
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--effort", default=DEFAULT_EFFORT, choices=EFFORTS)
    parser.add_argument("--thinking", type=int, default=0,
                        help="(deprecated) any value > 0 is treated as --effort high")
    parser.add_argument("--no-search", action="store_true", help="Disable web search")
    parser.add_argument("--wait", type=int, default=0,
                        help="Seconds to sleep between passes (rate-limit tiers)")
    parser.add_argument("--no-wait", action="store_true", help="(deprecated, now the default)")
    parser.add_argument("--sequel", action="store_true", help="Include sequel/spinoff episodes")
    parser.add_argument("--max-episodes", type=int, default=20)
    parser.add_argument("--persona", default="", help="Companion persona YAML for context")
    parser.add_argument("--output", "-o", default="")
    args = parser.parse_args()

    effort = "high" if args.thinking > 0 else args.effort
    persona_text = Path(args.persona).read_text(encoding="utf-8") if args.persona else ""

    result = generate_episodes(
        args.name, args.source, args.desc, llm=LLM(Keys.from_env(), progress=print_progress),
        model=args.model, effort=effort, output_lang=args.lang, web_search=not args.no_search,
        include_sequel=args.sequel, max_episodes=min(args.max_episodes, 30),
        persona_text=persona_text, rate_limit_wait=args.wait, progress=print_progress)

    print(f"\n   📊 Episodes found: {result.episode_count}")
    if result.valid:
        print("✅ Episode YAML validation: PASSED")
    else:
        print("⚠️  Episode YAML Validation Issues:")
        for issue in result.issues:
            print(f"   - {issue}")

    safe_name = args.name.replace(" ", "_")
    default = f"{safe_name}_Episode_full.yaml" if args.sequel else f"{safe_name}_Episode.yaml"
    path, ok = save_episodes(result.yaml_text, args.output or default, result.issues)
    if not ok:
        print(f"\n❌ YAML parse error — saved as: {path}")
        return 1
    print(f"\n📁 Episode Memory saved to: {path} ({len(result.yaml_text):,} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
